name: Deployment Workflow

on:
  push:
      branches:
        - main
        - test

jobs:
  build-and-deploy:
    name: 'Build'
    runs-on: ubuntu-latest
    environment: test
    concurrency: test

    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
        
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: '.'

  loadTest:
    name: 'Load Test'
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment: test
    concurrency: test

    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
          
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
                    
      - name: 'Run Load Test'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'SampleApp.yaml'
          loadTestResource: ${{ vars.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ vars.LOAD_TEST_RESOURCE_GROUP }}
          env: |
            [
              {
              "name": "webapp",
              "value": "${{ vars.AZURE_WEBAPP_NAME }}.azurewebsites.net"
              }
            ]          
      
      - uses: actions/upload-artifact@v2
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest/results.zip

  promote-to-prod:
    name: 'Deploy to Production'
    needs: loadTest
    runs-on: ubuntu-latest
    environment: production
    concurrency: production

    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
        
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: '.'
